title: YEG City Critic
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A site to voice your opinions about subject areas in the city of Edmonton
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rad-dice.cloudvent.net" # the base hostname & protocol for your site, e.g. http://example.com

# External Services
facebook_page:
linkedin_page:
twitter_username:
disqus_shortname: prototype-sites

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  category:
    output: true

defaults:
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
      comments: true