title: YEG City Critic
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A site to voice your opinions about subject areas in the city of Edmonton
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# External Services
twitter_username:
github_username:
disqus_shortname:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed